version: '3'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT_PREFIX}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./home:/home
      - ./src:/var/www
      - ./nginx/${NGINX_CONF}:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      
  php:
    build:
      context: .
      dockerfile: Dockerfile  
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: my-project:${PROJECT_PREFIX}
    container_name: ${PROJECT_PREFIX}_php
    volumes:
      - ./home:/home
      - ./src:/var/www

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_PREFIX}_mysql
    tty: true
    volumes: 
      - ./home:/home
      - ./db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PMA_VERSION}
    container_name: ${PROJECT_PREFIX}_pma
    links:
      - mysql
    volumes:
      - ./home:/home
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    ports:
      - ${PMA_PORT}:80
